---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uml-account
spec:
  selector:
    matchLabels:
      app: uml-account
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uml-account
    spec:
      containers:
        - name: api
          image: gabriellonestone/uml-account-api:<VERSION>
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 3000
        - name: front
          image: gabriellonestone/uml-account-front:<VERSION>
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: uml-account-api
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 80
      targetPort: 3000
  selector:
    app: uml-account
---
apiVersion: v1
kind: Service
metadata:
  name: uml-account-front
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 80
      targetPort: 80
  selector:
    app: uml-account
