---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uml-gateway
spec:
  selector:
    matchLabels:
      app: uml-gateway
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uml-gateway
    spec:
      containers:
        - name: uml-gateway
          image: gabriellonestone/uml-gateway-api:<VERSION>
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: uml-gateway
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 80
      targetPort: 3000
  selector:
    app: uml-gateway
