---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uml-portal
spec:
  selector:
    matchLabels:
      app: uml-portal
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uml-portal
    spec:
      containers:
        - name: uml-portal
          image: gabriellonestone/uml-portal-front:<VERSION>
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: uml-portal
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 80
      targetPort: 80
  selector:
    app: uml-portal
